version: '2'
services: 
    mra9776_c1:
        container_name: mra9776_c1
        build:
            context: .
            dockerfile: Dockerfile
        image: mra9776/dockerBike
        expose: 
            - 8080
        logging: 
            driver: json-file
    